### ISSUE TITLE
Computing relevance  for intermediate conv layer 

### ISSUE THREAD

**Issue by twmht** [lmzintgraf/DeepVis-PredDiff#4]
Hi,

Do you have plan for providing the implementation for computing relevance of intermediate conv layer ?

as paper said,

```
Deep Visualization of Hidden Network Layers 

Our third main contribution is the extension of the method to neural networks; to understand the role of hidden layers in a DNN. Figure 5 shows how different feature maps in three different layers of the GoogLeNet react to the input of a tabby cat (see figure 6, middle image). For each feature map in a convolutional layer, we first compute the relevance of the input image for each hidden unit in that map. To estimate what the feature map as a whole is doing, we show the average of the relevance vectors over all units in that feature map. The first convolutional layer works with different types of simple image filters (e.g., edge detectors), and what we see is which parts of the input image respond
```

thanks.

**Comment by lmzintgraf** [comment]
Hi,

this is already provided in the current implementation.

For my default experiment, in experiments_imagenet.py line 40, you can pick the layer for which you want to compute the relevance. Currently the default experiment is run for the output layer (called 'prob' in most caffe models), but you can for example pick 'conv1' for alexnet. Most layers for the caffe models I used I have listed in comments (lines 43-45) so you can pick something from there if you wish.

If you want to use your own classifier, you have to create your own target_func (see line 98 in experiments_imagenet.py for reference). This maps the input image to the output layer for which you want to compute the prediction difference - so this can be the output layer (or single class in the output layer), or any intermediate layer (or single node in the network).
